Fix AttributeError: Frame is None
```
  File "src/long_exposure.py", line 80, in local_video
    long_exposure()
  File "src/long_exposure.py", line 48, in __call__
    b_curr, g_curr, r_curr = cv2.split(frame.astype("float"))
AttributeError: 'NoneType' object has no attribute 'astype'
```